/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentrecordmanagement;

import com.sun.corba.se.impl.encoding.CachedCodeBase;
import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static java.sql.Types.NULL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTabbedPane;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ankit
 */
public class AttendanceRecord extends javax.swing.JFrame {

    /**
     * Creates new form AttendanceRecord
     */
    public AttendanceRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Date : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 20, 70, 24);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(310, 70, 60, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 460, 87, 30);

        jDateChooser1.setDate(new java.util.Date());
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(300, 20, 130, 30);
        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 2, 2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Atttendance"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(110, 110, 450, 300);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Year : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 70, 70, 24);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(280, 460, 73, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 444, 160, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\STUDY MATERIAL\\Java\\NetBeansProjects\\StudentRecordManagement\\src\\images\\Login_Page_Mockup_by_OGarciaDesign.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 666, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public void clear()
        {
            for(int i=0;i<jTable1.getRowCount();i++)
                for(int j=0;j<jTable1.getColumnCount();j++)
                 jTable1.setValueAt(" ", i, j);
        }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
            // TODO add your handling code here:
            String year = jComboBox1.getSelectedItem().toString();
          //  System.out.println(year);
            java.util.Date d = jDateChooser1.getDate();
            System.out.println("date "+d);

            Connection c=connection.connect();
            String query="insert into ";
            if(year.equals("1"))
             query+="attendancerecordfirstyr(sname,attendance,date) values (?,?,?)";
            else if(year.equals("2"))
             query+="attendancerecordsecondyr(sname,attendance,date) values (?,?,?)";
            else if(year.equals("3"))
             query+="attendancerecordthirdyr(sname,attendance,date) values (?,?,?)";
            else if(year.equals("4"))
             query+="attendancerecordfourthyr(sname,attendance,date) values (?,?,?)";
            
            
            System.out.println(query);
            PreparedStatement p=c.prepareStatement(query);
          // date which we get is object of java.util.Date class but sql select object of 
            // java.sql.Date
            
            // first we have to convert java.util.Date in java.sql.Date
           
            clear();
            long time = d.getTime();
            System.out.println("time "+time);
            java.sql.Date date = new Date(time);
            System.out.println("date "+ date);
            String temp="false";
            
            for(int i=0;i<jTable1.getRowCount();i++)
            {
                            //        System.out.println("INSIDE FOR loop");

                if(jTable1.getValueAt(i,0)!=null)            
                {
                    System.out.println("INSIDE IF");
         p.setString(1,jTable1.getValueAt(i,0).toString());
         p.setString(2,jTable1.getValueAt(i,1).toString());
         p.setDate(3, date);
         int row=p.executeUpdate();
         if(row>0)
               temp="true";
         else
             temp="false";
                
                }      
            }
            System.out.println("outside loop");
            if(temp.equals("true"))
            {
                System.out.println("hello");
                jLabel1.setText("insertion successful");
            }
            setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(AttendanceRecord.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try {
            // TODO add your handling code here:
            Connection c=connection.connect(); 
            String text=jComboBox1.getSelectedItem().toString();
            String query="select name from studentrecord where Year like '"+ text + "%'";
            PreparedStatement p=c.prepareStatement(query);
            ResultSet rs=p.executeQuery();
            // how to remove table contents 
            /*while(jTable1.getRowCount()!=0)
            {
                
                
            
            
            for(int j=jTable1.getRowCount()-1; j>=0;j--)
            {
               jTable1.remove(j);
                
            }
           
           
            }*/
            int i=0;
            if(rs.next())
            {
                do
                {
                    jTable1.setValueAt(rs.getString("name"), i, 0);
                    i++;
                }while(rs.next());
                rs.close();
                c.close();
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AttendanceRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        afterLoginPage2.main(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendanceRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
